.PHONY: build check test

build:
	go build -trimpath -o bin/deplexo ./cmd/deplexo

test:
	go test -race ./...

check:
	go build ./...
	go vet ./...
	go test -race ./...
	golangci-lint run --timeout 5m
	govulncheck ./...
